//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTCO.InspectionMobileApp.Model.LocalModel
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;

    public partial class ty202_template_type
    {
        public ty202_template_type()
        {
            this.cc301_inspection = new HashSet<cc301_inspection>();
            this.ty203_template_form = new HashSet<ty203_template_form>();
        }
    
        public long template_type_cd { get; set; }
        public long program_cd { get; set; }
        public string template_type_enm { get; set; }
        public string template_type_fnm { get; set; }
        public System.DateTime date_created_dte { get; set; }
        public Nullable<System.DateTime> date_deleted_dte { get; set; }
        public System.DateTime date_last_update_dte { get; set; }
        public decimal user_last_update_id { get; set; }
    
        public virtual ICollection<cc301_inspection> cc301_inspection { get; set; }
        public virtual ty201_program ty201_program { get; set; }
        public virtual ICollection<ty203_template_form> ty203_template_form { get; set; }
    }
    public class ty202_template_typeConfiguration : EntityTypeConfiguration<ty202_template_type>
    {
        public ty202_template_typeConfiguration()
        {
            this.ToTable("SIRS.ty202_template_type");
            this.HasKey(s => s.template_type_cd);
            this.HasMany(m => m.cc301_inspection).WithRequired(s => s.ty202_template_type);
            this.HasMany(m => m.ty203_template_form).WithRequired(s => s.ty202_template_type);
            this.Property(e => e.template_type_cd);
            this.Property(e => e.program_cd);
            this.Property(e => e.template_type_enm);
            this.Property(e => e.template_type_fnm);
            this.Property(e => e.date_created_dte);
            this.Property(e => e.date_deleted_dte);
            this.Property(e => e.date_last_update_dte);
            this.Property(e => e.user_last_update_id);
        }
    }


}
