//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTCO.InspectionMobileApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTCO.InspectionMobileApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English/Anglais.
        /// </summary>
        internal static string btnChooseEnglish {
            get {
                return ResourceManager.GetString("btnChooseEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French/Français.
        /// </summary>
        internal static string btnChooseFrench {
            get {
                return ResourceManager.GetString("btnChooseFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        internal static string btnFavorite {
            get {
                return ResourceManager.GetString("btnFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string btnFavorites {
            get {
                return ResourceManager.GetString("btnFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        internal static string butCopyPath {
            get {
                return ResourceManager.GetString("butCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string butView {
            get {
                return ResourceManager.GetString("butView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        internal static string columnHeaderFavourite {
            get {
                return ResourceManager.GetString("columnHeaderFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string columnHeaderFileName {
            get {
                return ResourceManager.GetString("columnHeaderFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path (full name).
        /// </summary>
        internal static string columnHeaderFilePath {
            get {
                return ResourceManager.GetString("columnHeaderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        internal static string columnHeaderFileSize {
            get {
                return ResourceManager.GetString("columnHeaderFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name/Folder Name.
        /// </summary>
        internal static string columnHeaderName {
            get {
                return ResourceManager.GetString("columnHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Folder.
        /// </summary>
        internal static string columnHeaderRootFolder {
            get {
                return ResourceManager.GetString("columnHeaderRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this folder or file!.
        /// </summary>
        internal static string errorMsgUnautorizedAccessMessage {
            get {
                return ResourceManager.GetString("errorMsgUnautorizedAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted File or Folder.
        /// </summary>
        internal static string errorMsgUnautorizedAccessTitle {
            get {
                return ResourceManager.GetString("errorMsgUnautorizedAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language/Langue.
        /// </summary>
        internal static string lblChooseLanguage {
            get {
                return ResourceManager.GetString("lblChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        internal static string lblClearSearchResults {
            get {
                return ResourceManager.GetString("lblClearSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        internal static string lblDateCreated {
            get {
                return ResourceManager.GetString("lblDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        internal static string lblDateModified {
            get {
                return ResourceManager.GetString("lblDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found!.
        /// </summary>
        internal static string lblNoItemsFound {
            get {
                return ResourceManager.GetString("lblNoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string lblSearchResults {
            get {
                return ResourceManager.GetString("lblSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in Bytes.
        /// </summary>
        internal static string lblSizeInBytes {
            get {
                return ResourceManager.GetString("lblSizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string navHome {
            get {
                return ResourceManager.GetString("navHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Centre.
        /// </summary>
        internal static string navReferenceCentre {
            get {
                return ResourceManager.GetString("navReferenceCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string navSettings {
            get {
                return ResourceManager.GetString("navSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string navUserProfile {
            get {
                return ResourceManager.GetString("navUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favourites.
        /// </summary>
        internal static string tabHeaderMyFavourites {
            get {
                return ResourceManager.GetString("tabHeaderMyFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string tabHeaderReference {
            get {
                return ResourceManager.GetString("tabHeaderReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tabHeaderSearch {
            get {
                return ResourceManager.GetString("tabHeaderSearch", resourceCulture);
            }
        }
    }
}
