//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTCO.InspectionMobileApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class SirsUserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SirsUserSettings defaultInstance = ((SirsUserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SirsUserSettings())));
        
        public static SirsUserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UserID {
            get {
                return ((decimal)(this["UserID"]));
            }
            set {
                this["UserID"] = value;
            }
        }
    }
}
